# Generated by Django 3.0.7 on 2020-06-18 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=300)),
                ('role', models.TextField(choices=[('company', 'Empresa'), ('candidate', 'Candidato')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('salary', models.CharField(choices=[('0-1', 'Até 1.000'), ('1-2', 'De 1.000 a 2.000'), ('2-3', 'De 2.000 a 3.000'), ('3+', 'Acima de 3.000')], max_length=16)),
                ('requirements', models.CharField(max_length=1000)),
                ('min_education', models.CharField(choices=[('EF', 'Ensino fundamental'), ('EM', 'Ensino médio'), ('TEC', 'Tecnólogo'), ('ES', 'Ensino Superior'), ('POS', 'Pós / MBA / Mestrado'), ('PHD', 'Doutorado')], max_length=20)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Profile')),
            ],
        ),
    ]
